### PR TITLE
Music genre recognition using deep learning

### PR DESCRIPTION
**Pull request by ableabhinav**
Added an idea about using neural networks to recognize genre of a song with the help of spectrograms.

### CODE REVIEW

**Comment by NirantK** [comment]
Thanks @ableabhinav ! This is great!

**Comment by ableabhinav** [comment]
Thanks! This is my current project (Third Year CSE), So thought would be
helpful for others too.

**Comment by NirantK** [comment]
That's great! 

Do raise a PR with your work when it's ready from your end! 
Ideally, code as an example :)

**Comment by ableabhinav** [comment]
Sure, will do!

**Comment by NirantK** [comment]
Hey @ableabhinav - thought I'd dropby and ask if you ended up releasing the code around Music Genre Recognition?

**Pull request merged**
